#ifndef __USER_VERSION_H__
#define __USER_VERSION_H__

#define NODE_VERSION_MAJOR		0U
#define NODE_VERSION_MINOR		9U
#define NODE_VERSION_REVISION	5U
#define NODE_VERSION_INTERNAL   0U

#define NODE_VERSION	"NodeMCU 0.9.5"
#define BUILD_DATE	    "build 20150318"

#endif	/* __USER_VERSION_H__ */
